# Site settings
title: "ScorpiusZ's Blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Scorpiuszjj.github.io" # the base hostname & protocol for your site
github_username: Scorpiuszjj

timezone: Beijing
# Build settings
highlighter: pygments
permalink: /:categories/:title/

# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables

paginate: 10
